---
title: "Estimated Rate of NIR Emission"
author: "W. Bauer"
date: "11/30/2014"
output: html_document
---

A mole is $6.022\times 10^{23}$ (Avagadro's number) of molecules per liter. VSD and luciferase concentrations in tissue might be on the order of 1 micromole, or $6.022 \times 10^{17}$  molecules per liter. Since spatial resolutions on the order of millimeters are contemplated, cubic mm are an appropriate unit. Since a cubic mm is $10^{-6}$ liters, a micromole concentration corresponds to $6.022 \times 10^{11}$ molecules per cubic mm.

Since msec time resolutions are contemplated, and since existing VSDs have half-lives in the msec range, assuming 1 msec half-lives for VSDs is a reasonable heuristic.   

The light emitting protein, cypridina luciferase, has a half-life on the order of [1 hour](http://www.piercenet.com/product/pierce-cypridina-luciferase-glow-assay-kit) which implies chemical conversion, hence photon emission, per millisecond equal to a fraction, $1-(1/2)^{\frac{1}{60 \times 60 \times 1000}} \approx 2 \times 10^7$, of available molecules. At a micromole concentration, this implies $2 \times 10^{-7} \times 6.022 \times 10^{11} \approx 116000 \approx 10^5$ cypridina luciferase emissions per millisecond, per cubic mm.

Cypridina luciferase itself is unlikely to be used in conjunction with NIR emitting VSDs. Following the proposal, assume a red-shifted analogue, referred to below as "luciferase," can be developed.

Assuming the rate of luciferase emission is equal to that of cypridina luciferase and is essentially constant over time scales of interest, let $v$ be the number of VSD molecules per cubic mm which are excited and which eventually emit a NIR photon rather than relaxing through vibration. Then $v$ satisfies$$\frac{dv}{dt}= 10^5 \times \epsilon - \frac{1}{2}v$$where $\epsilon$ is the efficiency at which luciferase emissions excite NIR-emitting VSD molecules. A value for $\epsilon$ can only be guessed at this point, though the project proposal, page 8, figure 6, suggests it may be fairly high.

At steady state, $\frac{dv}{dt}=0.$ Hence, at steady state, $\frac{1}{2}v = 10^5 \times \epsilon$, and $v = 2 \times 10^5 \times \epsilon.$ Since half of these relax via NIR emission per msec, the rate of NIR photon emission is $10^5 \times \epsilon$ per cubic mm, per millisecond.

[download Rmd source file](emissions.Rmd)

