---
title: "Improved Display"
author: "W. Bauer"
date: "03/22/2015"
output: html_document
---

```{r}
fname <- "../data/subject04_crisp_v.rawb"
phantom <- readBin(fname, what="raw", n=362*434*362, size=1, signed=FALSE, endian="big")
dim(phantom) <- c(362, 434, 362)
slice <- phantom[100,,]
slice <- as.integer(slice)
dim(slice) <- c(434, 362)
lg <- c("Background", "CSF", "Gray Matter", "White Matter", "Fat", "Muscle", "Muscle/Skin", "Skull", "Vessels", "Around fat", "Dura mater", "Bone marrow")
mycolors=c("blue4", "palegreen", "grey40", "grey90", "yellow", "violetred3", "lightpink2", "grey60", "red", "orange", "black", "brown")
```

```{r}
disp_with_legend <- function(slice, main){
  slice <- rbind(slice, matrix(0, round(0.3*dim(slice)[1]), dim(slice)[2]))
  fin <- par("fin")
  mai <- par("mai")
  h <- par("fin")[2] - mai[1] - mai[3]
  w <- par("fin")[1] - mai[2] - mai[4]
  rhs <- dim(slice)[2]*w - dim(slice)[1]*h
  nr <- dim(slice)[1]
  nc <- dim(slice)[2]
  if(rhs > 0){
    dw <- rhs/nc
    dh <- 0
  } else if(rhs < 0){
    dh <- -rhs/nr
    dw <- 0
  } else {
    dw <- dh <- 0
  }
  par(mai=par("mai") + c(0, 0, dh, dw))
  image(1:nr, 1:nc, z=slice, col=mycolors, main=main, xlab="mm", ylab="mm")
  par(mai=mai)
  mar <- par("mar")
  bty <- par("bty")
  lg <- c("Background", "CSF", "Gray Matter", "White Matter", "Fat", "Muscle", "Muscle/Skin", "Skull", "Vessels", "Around fat", "Dura mater", "Bone marrow")
  legend('topright', lg, cex=.9, fill=mycolors)
  par(mar=mar, bty=bty, mai=mai)
  }
disp_with_legend(slice,"test")
```

