---
title: "Simulation of neuronal activity, II"
author: "W. Bauer"
date: "June 21, 2015"
output: html_document
---

According to the project proposal,

> we believe NIR fluorescence imaging can provide millimeter scale spatial resolution (on par with PET) Coupled with a superbly enhanced temporal resolution from the sub-hour scale in PET to real-time (sub-sec scale), this is expected to provide a transformative paradigm for in vivo imaging of the human brain.

Simulating and recovering spatio-temporal patterns of neuronal activity such as those recorded in craniotomized rodents have been discussed as an interim goal. Also according to the proposal,

> We may use the recent observation that the VSD signal at x can be lumped as a generalized single compartment representing the dominant neurons in the volume.$$-C_M \frac{\partial V(x,t)}{\partial t} = g_E(x,t)(V(x,t)-E_E) + g_I(x,t)(V(x,t)-E_I) + g_L(x,t)(V(x,t)-E_L)\:\:(Eq. 3)$$where $g_E(x,t)$ and $g_I(x,t)$ are generalized excitatory and inhibitory conductances indicating the total neuronal input to the area located at x. [The third conductance, $g_L$ is a leak conductance--W.]

The recent observation cited refers in part to Petersen et. al., [Spatiotemporal Dynamics of Sensory Responses in Layer 2/3 of Rat Barrel Cortex Measured In Vivo by Voltage-Sensitive Dye Imaging Combined with Whole-Cell Voltage Recordings and Neuron Reconstructions](http://www.jneurosci.org/content/23/4/1298.long) in which whole cell recordings from individual neurons were found to be strongly correlated with bulk VSD signals: "response latencies and kinetics of membrane potential changes are very similar to the local VSD responses." The change in membrane potential, $\Delta V_m,$ was proportional to the fractional change, $\Delta F / F_0,$ in VSD fluorescence over baseline. The constant of proportionality varied significantly from animal to animal and experiment to experiment but, once known, could be used to predict $\Delta V_m$ with as standard deviation of 2 mV given VSD signals from a 0.2 mm by 0.2 mm region surrounding the body of a calibrated neuron.

Integration of Equation 3 with respect to $x$ would not, in general, result in an equation of the same form unless the conductances, $g_E(x,t),\:g_I(x,t),\:and\:g_L(x,t)$ and VSD signals, $V(x,t),$ were constant with respect to $x$ over the region of integration. Since Equation 3 has the essentially the same form as that of a Hodgkin-Huxley model for a single neuron, the observation suggests that neurons in a 0.2 mm square area (of layers 2 and 3) are behaving as if subject to approximately the same excitation, inhibition, and leakage.

(CAVEAT: Even applied to an individual neuron, Hodgkin-Huxley conductances will be different for dendrites, cell body, and axons. However, the Hodgkin-Huxley model is a parallel electrical circuit, and a parallel arrangement of many such circuits will have the same form, provided the cell interior and exterior can be considered "wires" in which currents travel instantly from one point to another. This will not be true on time scales of milliseconds, hence a single compartment model would not apply, e.g., to generation and propagation of individual action potentials. At longer times scales applicability does not seem surprising. It is surprising, however, that a single compartment model, as in Equation 3, applies to multiple neurons. The exterior of multiple neurons might be modelled as a single wire or conducting volume over long enough time scales, but their interiors are clearly isolated and to a large exent insulated from one another.)


