---
title: 'Collection from the side'
author: "W. Bauer"
date: "01/03/2015"
output: html_document
---

```{r echo = FALSE}
f_b <- function(r, b) {
  r1 <- sqrt(r^2+b^2)
  b*.92^r1/(4*pi*r1^1.5)
  }

# Consider two points, a and b, a distance r_ab apart,
# and two circles, one of radius r_a centered at point a,
# the other of radius r_b centered at point b. Determine
# the angle at point b subtended by the intersection of
# those two circles.
b_angle <- function(r_a, r_b, r_ab){
  # Heron's formula for triangle area
  s <- (r_a + r_b + r_ab)/2
  A <- sqrt(s*(s-r_a)*(s-r_b)*(s-r_ab))
  # Taking base to be r_ab, A = r_ab*h/2
  h <- 2*A/r_ab
  # sin of the angle at b is h/r_b,
  # This angle is half the angle subtended
  return(2*asin(h/r_b))
}
```

```{r echo=FALSE}

net_fraction <- function(r_a, r_b, r_ab){
  r_b*b_angle(r_a, r_b, r_ab)*f_b(r_b, 10)
}

# r_ab is the distance between the center of the active area and the collector.
# r_a is the radius of the active area
# r_b is the radius of 1mm wide annulus centered at b (the collector). 
# The function estimates the arrival rate of photons from the
# intersection of this annulus with the active area. An emission
# rate of 10000 photons per square mm per msec is assumed but can
# be varied.
xplor <- function(r_a, r_ab, emission_rate=10000){
  r_b <- seq(r_ab-r_a, r_ab+r_a, by=1)
  temp <- net_fraction(r_a, r_b, r_ab)*emission_rate
  x <- r_b+r_a-r_ab
  plot(x, temp, type='l', lwd=2, xlab="distance into active area (mm)", ylab="net fraction", main=paste("distance of collector from active area =", r_ab-r_a, "mm"))
  temp2 <- x[which.max(temp)]
  text(temp2, mean(temp), paste("max at ", temp2, "mm"),  pos=4)
  abline(v=temp2, lwd=2, lty=2, col=2)
}

```

