---
title: "Summary, May 1, 2015"
author: "W. Bauer, R. Grdina"
date: "04/28/2015"
output: html_document
---

Taking our cue from section C.2.4 of the original proposal, we have concentrated first on forward models of light and ultrasound propagation in the human brain. We have not explicitly considered inverse problems except to note where forward models suggest difficulties for image recovery. To date, we have estimated [optical](http://wilcrofter.github.io/know_brainR/Rmds/jacques.html) and [acoustic](http://wilcrofter.github.io/know_brainR/Rmds/acoustic_properties.html) properties for the eleven tissue types of a voxelized [BrainWeb](http://brainweb.bic.mni.mcgill.ca/cgi/brainweb1?alias=subject04_crisp&download=1) phantom, and have written a photon level simulator for it.

**1 mm optical diffusion limit** Our photon level simulations are consistent with an optical diffusion limit of 1 mm, as [reported](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4102891/) in the literature. [We find](http://wilcrofter.github.io/know_brainR/Rmds/scattering_and_direction.html) that after 20 scattering events, the distribution of photon directions is indistinguishable from random, and that the vast majority of photons will undergo 20 scattering events before traveling 1 mm from their source. (We have not yet documented the latter result.) 

We thus confirm that NIR propagation in tissue is essentially diffusive, a random walk in an inhomgeneous, absorbing medium. Though randomization of individual photon direction poses spatial resolution difficulties for purely optical image recovery, it does allow for a voxel (or NURB) level optical propagation model which would require far less computation than simulation at photon level. 

**Ultrasound scattering is minimal.** Ultrasound scattering in tissue is about three orders of magnitude less severe than that of light (10 cm vs .1 mm scattering distance.) [Preliminary ultrasound simulations](http://wilcrofter.github.io/know_brainR/Rmds/tof_vs_distance.html) are consistent with approximate preservation of wavefront direction. Simulations indicate that distance from an acoustic source within the brain is essentially proportional to time of flight, despite that different regions of a wavefront will encounter tissue varieties in different proportions. (Ignoring refraction, the resulting adjusted R-squared is 0.9992. Taking refraction at bone and soft tissue boundaries may degrade this result somewhat.) Hence, the location of an acoustic source could theoretically be triangulated from measurements of delays between laser pulse excitation and ultrasound detections at the scalp.

**Ultrasound signal strength is probably adequate.** An optimistic [back-of-the-envelope estimate](http://wilcrofter.github.io/know_brainR/Rmds/energy_density.html) suggests that a micromolar concentration of voltage (or other) sensitive dye will develop acoustic pressures of about 1 kPa when externally excited by an NIR laser. Pressures on this order are probably detectable (Timothy Mullen and Darian Hadjiabadi, personal communication) and are comparable to figures of 0.8 kPa [cited](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4102891/) in the literature. Micromolar concentrations of dye are considered reasonable (Dean Wong and Albert Gjedde, personal communication.)

Thus a photoacoustic approach, Aim 3 of the original proposal, at this point seems to offer the best chance for millimeter scale spatial resolution. There are a number of caveats:

* Though gross signal strength may be adequate, the nature of ultrasound modulation by neuronal activity is not clear. Such modulation approximates a 10% shift of a dye's spectrum along the  wavelength axis. (See [LM Loew - Membrane potential imaging in the nervous system, 2011 - Springer](http://www.newbooks-services.de/MediaFiles/Texts/8/9781441965578_Excerpt_001.pdf) (PDF.)) Shifts in ultrasound intensity may be of the same order. However, Emad Boctor has suggested that neuronal activity may modulate the shape, not just the intensity, of ultrasound spectra.
* The longest peak absorption wavelength listed in Leslie Loew's review (*Ibid.*) for a voltage sensitive dye in lipid is 678 nm, slightly below near infrared (700 nm.) Optimal excitation of this dye would most likely be at a longer wavelength, but still at the lower end of near infrared. It seems likely that dyes with better NIR characteristics would be needed.
* Millimeter scale spatial resolution would require an ultrasound wavelength of the same scale, hence an ultrasound frequency on the order of 1 MHz. Dyes are likely to have relaxation half-lives on the order of a millisecond. Thus only 1/2000 of the excited dye molecules would relax per cycle of excitation. Heterodyning, in effect adding together signals from 1000 successive cycles, is probably well within the state of the art but may be expensive.
* Ultrasound from natural chromophores, as well as encapsulated dye still circulating in plasma, will likely be present.
